title = "checks-loa-ppag"

[packages]

[packages.sisor]
path = "https://raw.githubusercontent.com/splor-mg/sisor-dados-2024/main/datapackage.json"

[packages.sigplan]
path = "https://raw.githubusercontent.com/splor-mg/ppag-planejamento-dados-2024/main/datapackage.json"

[packages.auxiliares]
path = "https://raw.githubusercontent.com/splor-mg/volumes-loa-dados/main/datapackage.json"
resources = ["desc_setor_governo", "ffp_acoes"]
